# -*- coding: utf-8 -*-
"""trabalhoestoque.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TndCZcdJnuEplrV4ZZEU5kTiDoyMB5o3
"""

#testeGit

from datetime import datetime
import matplotlib.pyplot as plt

import sqlite3
conn = sqlite3.connect("estoque.db")
cur = conn.cursor()

cur.execute("""
CREATE TABLE IF NOT EXISTS produto(
            nome TEXT NOT NULL,
            categoria TEXT NOT NULL,
            preco REAL NOT NULL,
            quantidade INTEGER NOT NULL,
            data TEXT NOT NULL
);
""")
conn.commit()

produtos = []

while True:
    print("\n=== MENU ===")
    print("1 - Cadastrar produto")
    print("2 - Excluir produto")
    print("3 - Mostrar relatório")
    print("4 - Gerar gráfico")
    print("5 - Sair")

    opcao = input("Escolha uma opção: ")

    if opcao == "1":
        nome = input("Nome do produto: ")
        categoria = input("Categoria: ")
        preco = float(input("Preço: "))
        quantidade = int(input("Quantidade Inicial:"))
        data_cadastro = datetime.now().strftime("%d/%m/%Y %H:%M:%S")

        cur.execute("""
          INSERT INTO produto(nome, categoria, preco, quantidade, data)
          VALUES(?, ?, ?, ?, ?);
          """, (nome, categoria, preco, quantidade, data_cadastro))
        conn.commit()

        print(f"Produto: {nome} cadastrado com sucesso!!")

    elif opcao == "2":
     nome = input("Digite o nome do produto a se excluir: ")
     cur.execute("DELETE FROM produto WHERE LOWER(nome) = LOWER(?) ", (nome,))
     conn.commit()
     if cur.rowcount > 0:
         print(f"Produto: {nome} removido com sucesso")
     else:
         print(f"Produto: {nome} não encontrado")

    elif opcao == "3":
        cur.execute("SELECT nome, categoria, preco, quantidade, data FROM produto")
        produtos = cur.fetchall()

        if not produtos:
            print("Nenhum produto cadastrado")
        else:
            print("\n=== Relatório de produtos ===")
            for p in produtos:
                if p[3] < 3:
                    print(f"{p[0]} | {p[1]} | R${p[2]} | Qtd: {p[3]} Cuidado!!⚠️ Estoque baixo | Data: {p[4]}")
                else:
                    print(f"{p[0]} | {p[1]} | R${p[2]} | Qtd: {p[3]} | Data: {p[4]}")

    elif opcao == "4":
        cur.execute("SELECT categoria, quantidade FROM produto")
        categ = [p[1] for p in produtos]
        quantidades = [p[3] for p in produtos]

        plt.bar(categ,quantidades)
        plt.title("Quantidade de Produto em Estoque")
        plt.xlabel("Categoria de produto")
        plt.ylabel("Quantidade em Estoque")
        plt.xticks(rotation=45, ha='right')
        plt.tight_layout()
        plt.show()

    elif opcao == "5":
        print("Saindo do programa!!")
        break
    else:
        print("Opção invalida. Tente novamente!")